# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4686ec381e6da1d2a3443dd34d386f5d30aa2f9db9cb3627faae467a32bbd40664838bcd80a69edf02842ffef9f8dd4f62d031b34eedbb080dc331c697da8796

test:
  secret_key_base: 95dbab5ca585b0cc923f27addbd0419bc5ec019a0c8077db5fb8f2392c9e6018c0e2a729d9bd5d1fc097a7c9146ffddcd2001593528b3de2decb33faf4ffff82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
